/**
 *Submitted for verification at Optimistic.Etherscan.io on 2023-01-20
*/

// SPDX-License-Identifier: MIT

// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK00OkkkxxdddoooooodddxxkkkO0KKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXK0kxdoolllllodddxxxkkkkkkkkxxxddoollllloddkO0KNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0OxolllldxkOO0KXXXXXXXXXXNWWWNXXXXXXXXXXXK0OkxxolllldxOKXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOxollloxk0KXXXXK0OkkxxdddddolONWNOolddddddxxkkO0KXNNXK0kxollldxOXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOxoccoxk0XXXNWWXxooddxkkO00KKXKxckNNNOcdKXXKK0OOkxxdoodKWWXXXNX0kdollox0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkoccoxOKXXKOkdoxXWXxcdKNWWWWWWWWWNklxNNXkcxXNWWWWWWWWWXkcdXWKdloxk0KNXKOxlcldkKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkocldk0XXKOxdodxkdcxXWKol0XXK0XWXOxddocxNNXkcldddkKWNK0KX0olOWNxcdOkxoodk0XNX0koccdkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkoccdOKNX0kdodxOKNWWKolONNkllooolxNXdcdO00KNWNX000klo0W0lloolcxXNOloKWWNXKOxoodkKXX0koccdOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMN0xlcokKNX0xoodOKNWWWNXKkocdKWX0O0KKdoKNklkNWWWWWWWWWW0ldXNxlkXK00XWXxclxOKNWWWWX0kdlokKNX0xlclxKNMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMNOoccdOXNWWKd:o0NWWNNNWKdcokOKNWWWWWNXxlkN0llxkxxxxxxxkxockNKoo0NNWWWWNX0OdllONNXXWWWKocdKNNXNXOoccd0NMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMWXkoclxKNXOdkXNKxld0KOdokXNklxXWWNXKOkxdollkNXkxxkkkkkkkkkxxkKNKdloodxkOKXNWNklxXXklox0OolkXNKdldOXX0dccoONMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMNOl:lkKNKkololoONXOlcloddlxXXkldkxoolodxkO00KK00OOkkkxxxxkkkOO00K000OkxdolodxxlxXXxldkdlco0NXkllxdlokXX0xcco0NMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMNOo:lxKNKxlokKX0dlxKNKk0XNXkldKXkloxkO00OkxdollcccclllooooollllccccllodxkO00OkdoxKKdlkXWNK0XN0dcdKNN0xlokKX0dccd0WMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMWKdccdKNKxlokXNWNXxcckXWWWNNKxlckXNK00kdlc:clodxkO0KKXXXXXNNNXXXKKK0Okxdolcccodk0KXNOocdOKNWWWNOocoOXNNNKxllkXX0o:cxXWMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMNkc:oOXXkllkXNNWXklcd0NNWNKkolox00Oxoc:cldxOKXNNWWWWNWWWWWWWWWWWWWWWWNNNNNX0Oxdlccldk00OxoldOXNWNXkl:dKNWWNKxloOXXkl:lONMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMWKo:cxXXOolxKNNNXXX0ocd0NXOdllx0KOdl:coxOKXNNWWNWWWWNWWNNWWWWNNNWWWWWNNNNWWNNWWNNX0kdl:clxOKOdllx0X0dld0XKKXNWN0ocd0NKd::xXWMMMMMMMMMMMMM
// MMMMMMMMMMMMNOc:o0NN0o:lOXNXOolxKXOoldoldO00xl:cok0XNWNNWWWWWWNNNNNWNNNNWNNNNWNWWNNNNNNNNNNNNNNNNNX0xo::lx00kollld0XKklcoOXKklcoONNXkl:o0WMMMMMMMMMMMM
// MMMMMMMMMMMXx::dKNXXNKkolodocdxdox0XOdx0Kko::lk0XNWNNNNNNNNNNNNNNWNNNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNX0xl:cdOKOxOXKxookkocllld0XNNNXN0o:ckNMMMMMMMMMMM
// MMMMMMMMMWXd:ckXXklok0XX0xloOXNXkcckXNKkl:cdOXNNNNNNNNNNNNNNNNNNNNNNNNNNX0kkOKNNNNNNNNNNNNNNNNNNNNNNNNNNKko::oOXN0l:oKNNXkdkKNNX0kooONKd::xXMMMMMMMMMM
// MMMMMMMMWKo;cOXKdcldolox0XXXNNNOocoOKkl:cd0NNNNNNNNNNNNNNNNNNNNNNNNNXKkdllcclldk0XNNNNNNNNNNNNNNNNNNNNNNNNXOd::oOKOlcd0NNNNNN0kollolckXXx::dXMMMMMMMMM
// MMMMMMMWKo;cONKocdKNXOl;o0NNNKxcckKOl;cd0NNNNNNNNNNNNNNNNNNNNNNNNKOxolllllooollllodkKXNNNNNNNNNNNNNNNNNNNNNNXOo::o0KxcckXNNNOl:oOXN0ocxXXx::dXMMMMMMMM
// MMMMMMMKo;cONKo:dXNNXkclONNN0o:o00d::o0XNNNNNNNNNNNNNNNNNNNNNX0kdllllloodkO0OkddolclloxOKNNNNNNNNNNNNNNNNNNNNNXkl;cxKOl:dKNNXkclOXNNKocxXXx:;dXMMMMMMM
// MMMMMMXd;:kXKo:dKNNN0o:lk0KOccxKOl;ckXNNNNNNNNNNNNNNNNNNNXKOdollllodxkOOKKXXXKK0Okxdolclodk0XNNNNNNNNNNNNNNNNNNNKd::o00d:l0XKkl:o0NNNKo:xXXx::xNMMMMMM
// MMMMMNx;:xXKd:dKNNXKKK0kdol:ckKx:;o0NNNNNNNNNNNNNNNNNNX0xolllloodk0XNK0XNNNNNNNX0KXX0kxolclloxOKXNNNNNNNNNNNNNNNNXOc;ckKx:coooxOKKXNNN0l:xXKo;:OWMMMMM
// MMMMWO:;oKXx:oKNNXxcldk0KKOk0Kd;;dKNNNNNNNNNNNNNNNX0kdlllloodxOKNNNNN00XNNNNNNNX00XNNNNKOxdolclldx0XNNNNNNNNNNNNNNN0l;:xKOxk0K0kdllOXNNOccON0l;l0WMMMM
// MMMWKl,l0N0l;lxO0xccxxolloOXKd;:dKNNNNNNNNNNNNXKOxollllodxk0XNNNNNNNNX0KXNNNNNXK0KNNNNNNNNXKOxdlcclodkKXNNNNNNNNNNNNKo;:xXXkolloxo:cO0Oxc;oKNk:;dXMMMM
// MMMNx;:kXNKOkdolc::kXNXkc:kKd;;dXNNNNNNNNNNX0kdlllloddkOKXNNNNNNNNNNNNXK00000000XNNNNNNNNNNNNXKOxdolccloxOKNNNNNNNNNN0o;:kKx:lOXNXd:cllodxOXNXd;:kWMMM
// MMW0c;oKX0kO0KXK0O0XNNKo:xKx:;oKNNNNNNNXKOdoloodolccodxxxxxxxxxxxxxxxxxxxdddddxxxxxxxxxxxxxxxxxxxdocclooolldk0XNNNNNNN0l;cOKo:dXNNKOOKKXK0Ok0N0c,lKMMM
// MMNd;:kX0l;cllooxOXNNXx:o0Oc,l0NNNNNX0koc:;:lolllccccccclcclccccccclllllccccccclccccccllccclcccclcccccclol:;;cox0XNNNNXOc,l00c:kXNNXOdollc:;oKXd;:kWMM
// MM0c,lKXx:l0KOx:;dXNN0c:k0o,:kXNNNNNK0OOOOOOOOkoccccccccclxOOxlcccccccccokOOkoccccccccclxOOdc:ccccccccokOOOOOOOO0XNNNNNXx;;dKx:lKNNKo;cxO0kc:kXOc,oXMM
// MWk;;xXKl:xXNNk::kKXKd;oKk:;dKNNNNNNNNNNNNNNNNXkl:::::::co0NN0oc:::::::lkXNNXkl:::::::cd0NN0o::;;;;::lOXNNNNNNNNNNNNNNNN0l,cO0l:kXXKx;c0NNXd;dXKo,:OWM
// MNo,:ONO:cONNXklcllol::k0l,:ONNNNNNNNNNNNNNNNXOxxdc:::codxkK0kxdl::::ldxx0K0Oxxoc:::codxkK0kxdlcc:cldxk0XNNNNNNNNNNNNNNNXx;;dKx;:oollclONNXk:l0Xx;;xNM
// MKl,l0Xx;lKNNXK0000OkkOKO:,lKNNNNNNNNNNNNNNNNKdlxOxooookkookkooOkooooxOdlxOkdlxOdooodkklokxldOxooookOdlxXNNNNNNNNNNNNNNNNOc,l0KkkkOO00KXNNN0c:kXO:,oXM
// W0c,oKKo;dXNX0lcloooodOXx;;dXNNNNNNNNNNNNNNNNXK0K0xoollkK00XX0KKxlloox0K0KXXK0K0dooloOK0KXXKKKxllllxKK0XNNNNNNNNNNNNNNNNNKo,:OXOxdddooldKNNKl;xX0c,lKM
// WO:,oKKl;xXNXk::xOOxc,dKd,;kXNNNNNNNNNNNNNNNNNNNNKxoollkXNNNNXNXxloodxKNNNNNNNX0dooooOXNNNNNNKdllllxKNNNNNNNNNNNNNNNNNNNNXd,;xKo;cxkko;c0NNKo;dXKl'c0W
// Wk;,dX0l,coodc,l0NN0l;d0o,:OXNXXXXXXXXXXXNXXNNNNNKdoollkXXNXXNNXxloodxKNXXXXXNX0dooookXNXNNXNKdllllxKNNXNNNNNNNNXXXXXXXXNXx;,dKd;oKNNO:;lddo:,oKKo,:OW
// Wx,,dX0l,,,''',lKNX0c;x0l':OXXNXXXXXXXXXXXXXXXXXNKdoollkXXXXXXXXxlooox0XXXXXXXX0doolokXXXXXXNKxllclxKNXXXXXXXXXXXXXXXXXXXXx;,dKd,lKNNOc,,,,,,,oKKo,:OW
// Wk;,dX0c,:lolc,l0XX0c;xKo':kXXXXXXXXXXXXXXXXXXXXX0dolllkXXXXXXXKxlloox0XXXXXXXX0doolokXXXXXXXKdllclxKXXXXXXXXXXXXXXXXXXXXXx;,d0o,oKXXO:;clll;,oKKl':OW
// WO;,oK0l;dKXXk;:xOkx:,xKo,;kXXXXXXXXXXXXXXXXXXXXX0dolllkXXXXXXXKxlloox0XXXXXXXX0doolokXXXXXXXKdclclxKXXXXXXXXXXXXXXXXXXXXXd,;x0l,lO00x;cOXXKo,dK0l':0W
// WO:'lKKl,dKXXOl:llloodOKd,,dKXXXXXXXXXXXXXXXXXXXX0dolclkXXXXXXXKxcloox0XXXXXXXX0doolokXXXXXXXKdccclxKXXXXXXXXXXXXXXXXXXXXKl';kKxlllllc;l0XX0l,dX0c'c0W
// WKc'c0Xd,l0XXXK0000OOkOKk;'l0XXXXXXXXXXXXXXXXXXXX0dllclkXXXXXXXKxcloox0XXXXXXXXOooolokXXXXXXXKdccclxKXXXXXXXXXXXXXXXXXXXXO:'cOKOOOO0OOO0XXXOc;kXO:'lKM
// MXo';kXk;:OXXXklccllc;:k0c':kXXXXXXXXXXXXXXXXXXXX0dllclkKXXXXXXKxcloox0XXXXXXXXOololokXXXXXXXKdccclxKXXXXXXXXXXXXXXXXXXXXx;'o0d;:cllcloOXXXk;cOXd,,dNM
// MNx,,dX0c;xXXXx,;x0K0l,o0x,,oKXXXXXXXXXXXXXXXXXXX0olcccxKXXXXXXKdcclld0XXXXXXXXOollclkKXXXXXX0occ:cd0XXXXXXXXXXXXXXXXXXX0l';k0c;d00Oo,:OXXKo,lKKl';kNM
// MW0:'c0Kd,lO0Od;,dKXXk::k0c';kXXXXXXXXXXXXXXXXXX0dc::::lOXXXXXKkc::::cxKXXXXXXOo:::::oOXXXXXKxc::::cxKXXXXXXXXXXXXXXXXXKd,'o0x;cOXX0l,ck0KO:;xXO:'c0WM
// MMXo';xXO:,::::clxKXXKo,l0x;'c0XXXXXXXXXXXXXXXX0d:;;;;;;lkKXXKkc;;;;;;:d0XXXX0o:;;;;;:lOKXXKxc;;;;;;cd0XXXXXXXXXXXXXXXXk:':OOc;xKXX0dlcccc;,c0Kd,,dNMM
// MMWO:'l0KkdxkO0K0OOKXXOc,d0o,'oKXXXXXXXXXXXXXXKd:;;;;;;;;ckXXOc;;;;;;;;:dKXXKd:;:;;;;;:lOXXkc;;;;;;;;:xKXXXXXXXXXXXXXXOc';x0o,l0XXKOO000OkddkXO:':0WMM
// MMWXo',xXXKOxdlc:;;xKXKx;;x0l',dKXXXXXXXXKOxxxdl:::::::::coxxoc:cccc:cccldxxdlccccccccccoxxoccccccccccodxxxOXXXXXXXXX0l',d0d,:kXXKd;;:lodk0KXKo',dNWMM
// MMMW0c':OXk:':oxko,:ddlc:cxKOc',dKXXXXXXX0dllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllxKXXXXXXX0l',o00d::coxd;;dxdc;'cOXx;'c0WMMM
// MMMMNk;'l00o,c0XX0o;:coxOOxxOOc',o0XXXXX0dlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllld0XXXXXOl',o0OkO0kdlc;;dKXXk:,dKOc.;kNMMMM
// MMMMWXd',dKOc,o0XX0OOOkdlc:,:xOl''cOKXKOdlcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccclx0XXKk:',dOd;,:cok00OOKXXOc,o00l',dXWMMMM
// MMMMMWKl';xKO:,o0XXKx:,cdOOd,;dOd,';xKKOdoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooox0X0d;';xOo,;dkxl;;o0XXX0c,l00o,'oKWMMMMM
// MMMMMMW0c';xKk:,o0XX0l,:kKXKx;,lOk:',lOKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKkc''lkkc,:kKXKx;;d0XX0l,c00d,'l0WMMMMMM
// MMMMMMMW0c';kKk:,o0K0x;':OXXKkc,:xOo;.,oOKXKXXXKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKXKkl,':xOd;,lOKXKx;'cOKKOc,lOKd,'c0WMMMMMMM
// MMMMMMMMN0c';xKOc,:l:;:lk0KKXX0d;,lkkl,.;oOKXKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKXXXXXXKXXKkl,';oOxc,:xKXKKKOdc;;co:,l00d,'c0NMMMMMMMM
// MMMMMMMMMN0l',d00l,;lx0KK0xokKKKx;.:kKkl,.;lkKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKXKKXK0xc,.;oOKOc';xKK0d:cx0KOdc,;d00o''l0WMMMMMMMMM
// MMMMMMMMMMWKo,,o00O0KX0kl;,,,lxd:;lk0xdkkl,''cdOKKKXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKKKKKXKKOo:'';okxookOd::odc,;:;;lk0KOOKOc',oKWMMMMMMMMMM
// MMMMMMMMMMMWXx;':kKK0d:,;okkl,,;lk0xc;,;lxkd:'',cdOKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0Odc,.,cxkxc,;;;lkOd:,;dO0kl,'lOKKx;.;xXWMMMMMMMMMMM
// MMMMMMMMMMMMWNOc',o00d,'lOKKKkxO0kc,cxko:,:okxo:'.,cox0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOxl:'.,cdkxl;,:d0Od;;lO0kOKKKOl,;d0Ol''cONWMMMMMMMMMMMM
// MMMMMMMMMMMMMWNKd,':k0kc,;d0KKKKx;.;xKKK0xl;;coxxoc,'',:ldkO0KKKKKKKKKKKKKKKKKKKKKKKKKKKK0Oxdl:,.';cdxxo:,;ok0KK0x:.,d0KKKOo;,lO0x;.,dKNWMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMWXOc',lO0x:,:d0KK0kl,,lkKKKKOdc;,ckKOxoc;'.',;clodxkOO0000KKKK0000OOkxdolc;,'',:ldxOKOl',lx0KKKKOl',lOKKKOo;,ck0kc''cOXWMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMWNKx:',oO0d:,:dOKKx;':k0OO0KKOc'cOkl:ldxxdoc:;''..'',,;;;::::;;;,,''..',;:loxxxdl;:x0d,;xKK0xxO0d;,lO0Oo;,cx0kl'.:xKNWMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMWN0d;';oO0xc,;ll,,oO0d;';ld:,lOO:,::;,;:loddxdddoollccc::::ccclloodddxddoc:;,;:c,;x0x;,lc;'':k0Oc,;:,,ck0kl,.;dKNWMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMWN0d;',ok0kl,':x0Ol';ol;''lOOc,o00Okdl:;;,,,lO0xooooooddoooolld0Oc,,,;:cldkOKKx;;x0x:':oxl,,o00d:;lk0kc,';d0NWMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMWN0x:',cxOOkOKx:.:kKK0kk00l.'lxO0KKKK0Okl':OO:.;:::::::::::',kO:'lkO0KKKK0kxl,.cOKOO0KK0o'.cOK00Od:'':x0NWMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMWNKkl,':ok00d:',cdO0KKK0koc;',l0KOxkOOl'l0x,;kKKK00000KKO:'d0o'cOOkxk0Kx,.;cdO0KKK0kdc,,:dO0kl;',ckKNWMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMWNXOd:,,:dOOko:,,:oxO0KK0d,'dKk:.,;;',x0d',oxkk0KK0kxxd;.l0x,.,;,',dKO:.cOKK0Odl;,;cdkOko;'':dOXNWMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKko;',:okOOdc:,,:ldd;.l00l.;dxold00d;,;,',dKKk:.,;,;o00dodxxc.:OKx,.col;,,:lxOOxo:'';okKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNKko:,,;ldkOkdl:;'.:kKx,.l0KKKKKK00OOx,.oKKk,'oOO00KKKKKK0x,.o00d,';:lxOOkdc;',:okKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNKOdc;',;cdkOOkxkK0o'.,:clodxxkOOOx,'dKKk;.lOOOkxddolc:,''cOK0kkOOxoc;'';ldOKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXKOdl:,,,:loxOOOkxolc:;;;,,,,;,.'dKKk;.',,,,,;;::cloxkOOkxoc;,',:ldOKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK0xoc:,,,;:cloxkkkOkkkxxxddxOKK0kddxxxkkkOkkxdolc;,,,,:coxOKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXK0Oxol:;;,,,,;;::cccllloolllllcc::;;,,,,,;;:loxO0KXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXXK0Okxddolcc:::::;;;;:::::ccloodxkOKKXNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNXXXXXXKKKKKKXXXXXXNNNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

// a decentragora contract by 0xzenodotus

// https://decentragora.xyz

pragma solidity ^0.8.0;

contract PhraseToHex {
    function convert(string memory input) public pure returns (bytes memory output) {
        bytes memory inputBytes = bytes(input);
        output = new bytes(2 + (inputBytes.length * 2));
        output[0] = 0x78; // 0x78 = x
        output[1] = 0x30; // 0x30 = 0
        for (uint i = 0; i < inputBytes.length; i++) {
            uint8 b = uint8(inputBytes[i]);
            output[(i * 2) + 2] = hexDigit(b / 16);
            output[(i * 2) + 3] = hexDigit(b % 16);
        }
    }

    function hexDigit(uint8 input) private pure returns (bytes1) {
        if (input < 10) {
            return bytes1(input + 48);
        } else {
            return bytes1(input + 87);
        }
    }
}